# Generated by Django 3.1.3 on 2020-11-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0003_auto_20201126_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='pusername',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
