# Generated by Django 3.1.3 on 2020-12-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0005_postsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsdata',
            name='seen_no',
            field=models.IntegerField(default=0),
        ),
    ]
